services:
  placede:
    image: channelmirror
    restart: always
    environment:
      - BOT_TOKEN=discordBotToken
      - DB_USER=botUser
      - DB_PASSWORD=botPassword
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=botDatabase
      - EXTENTIONS=channelmirror
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    volumes:
      - ./volumes/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootPassword